[package]
name = "dockertui"
version = "0.1.0"
edition = "2024"

[dependencies]
dockertui-core = { path = "../dockertui-core" }

anyhow = "1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"

ratatui = "0.27"
crossterm = "0.28"

clap = { version = "4", features = ["derive"] }
portable-pty = "0.8"
